Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes

In [1]:
import numpy as np

# 1D array
arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:")
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("-" * 40)

# 2D array
arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print("2D Array:")
print(arr2)
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)
print("-" * 40)

# 3D array
arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print("3D Array:")
print(arr3)
print("Shape:", arr3.shape)
print("Dimensions:", arr3.ndim)
print("-" * 40)


1D Array:
[10 20 30 40 50]
Shape: (5,)
Dimensions: 1
----------------------------------------
2D Array:
[[10 20 30]
 [40 50 60]]
Shape: (2, 3)
Dimensions: 2
----------------------------------------
3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Dimensions: 3
----------------------------------------


Create:

an array of zeros of shape (3,3)

an array of ones of shape (2,5)

an array filled with 7


In [2]:
import numpy as np

# Array of zeros with shape (3, 3)
zeros_arr = np.zeros((3, 3))
print("Array of Zeros (3x3):")
print(zeros_arr)
print("-" * 40)

# Array of ones with shape (2, 5)
ones_arr = np.ones((2, 5))
print("Array of Ones (2x5):")
print(ones_arr)
print("-" * 40)

# Array filled with 7
sevens_arr = np.full((3, 4), 7)
print("Array Filled with 7 (3x4):")
print(sevens_arr)
print("-" * 40)


Array of Zeros (3x3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----------------------------------------
Array of Ones (2x5):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
----------------------------------------
Array Filled with 7 (3x4):
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
----------------------------------------


Create an array of even numbers between 10 and 50 using arange

In [3]:
import numpy as np

# Create an array of even numbers between 10 and 50
even_numbers = np.arange(10, 51, 2)

print("Even Numbers between 10 and 50:")
print(even_numbers)


Even Numbers between 10 and 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Create a 4×4 matrix from 0–15. Then , extract:

the first row

the last column

a 2×2 subarray from the center


In [4]:
import numpy as np

# Create a 4×4 matrix with values from 0 to 15
arr = np.arange(16).reshape(4, 4)

print("4×4 Matrix:")
print(arr)
print("-" * 40)

# Extract the first row
first_row = arr[0, :]
print("First Row:")
print(first_row)
print("-" * 40)

# Extract the last column
last_column = arr[:, -1]
print("Last Column:")
print(last_column)
print("-" * 40)

# Extract a 2×2 subarray from the center
center_subarray = arr[1:3, 1:3]
print("2×2 Subarray (Center):")
print(center_subarray)
print("-" * 40)


4×4 Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------------------------------------
First Row:
[0 1 2 3]
----------------------------------------
Last Column:
[ 3  7 11 15]
----------------------------------------
2×2 Subarray (Center):
[[ 5  6]
 [ 9 10]]
----------------------------------------


Add a 1D array [1,2,3] to each row of a 3×3 matrix

In [5]:
import numpy as np

# Create a 3×3 matrix
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Create a 1D array
arr = np.array([1, 2, 3])

# Add the 1D array to each row of the 3×3 matrix
result = matrix + arr

print("Original Matrix:")
print(matrix)
print("-" * 40)

print("1D Array:")
print(arr)
print("-" * 40)

print("Result (Matrix + Array):")
print(result)


Original Matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
----------------------------------------
1D Array:
[1 2 3]
----------------------------------------
Result (Matrix + Array):
[[11 22 33]
 [41 52 63]
 [71 82 93]]


Given two arrays A and B, compute:

(A + B) / 2

A**2 + B**2


In [6]:
import numpy as np

# Define two arrays
A = np.array([10, 20, 30])
B = np.array([40, 50, 60])

print("Array A:", A)
print("Array B:", B)
print("-" * 40)

# Compute (A + B) / 2
avg = (A + B) / 2
print("(A + B) / 2:")
print(avg)
print("-" * 40)

# Compute A**2 + B**2
sum_squares = A**2 + B**2
print("A**2 + B**2:")
print(sum_squares)


Array A: [10 20 30]
Array B: [40 50 60]
----------------------------------------
(A + B) / 2:
[25. 35. 45.]
----------------------------------------
A**2 + B**2:
[1700 2900 4500]
