In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)

arr = arr * 5

print(arr)
print(arr.shape)
print(arr.size)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
5
[ 5 10 15 20 25]
(5,)
5


In [18]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4, 5], # Row 1
     [6, 7, 8, 9, 10] # Row 2
    ])

print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
2
(2, 5)
10


In [19]:
import numpy as np

arr = np.array([
    [ [1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10] ],

    [ [11, 12, 13, 14, 15],
      [16, 17, 18, 19, 20] ]
])

print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
<class 'numpy.ndarray'>
3
(2, 2, 5)
20


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

arr = np.array([1.2, 2.5, 3.7, 4.9, 5.0])
print(arr.dtype)

arr = np.array([1, 2, 3, 4, 5.0])
print(arr.dtype)

arr = np.array([1, 2, 3, '4', 5.0])
print(arr.dtype)

int64
float64
float64
<U32


In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4, 128], dtype= np.int8)
print(arr.dtype)
print(arr)

arr = np.array([1, 2, 3, 'hi', 5.0], dtype= np.float64)
print(arr.dtype)
print(arr)

int8
[  1   2   3   4 120]


ValueError: invalid literal for long double: hi

In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
print(arr)

arr = arr.astype(np.float64)
print(arr.dtype)
print(arr)

int64
[1 2 3 4 5]
float64
[1. 2. 3. 4. 5.]


In [41]:
import numpy as np

arr = np.array([1, 2, 3, 4, 128], dtype= np.int16)
print(arr.dtype)

arr = arr.astype(np.int64)
print(arr.dtype)
print(arr)


int16
int64
[  1   2   3   4 128]


In [46]:
lst = [10, 20, 30, 45.5]

arr = np.array(lst, dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 45]
<class 'numpy.ndarray'>
int32


In [47]:
lst = [10, True, "Hello", 10.6]

arr = np.array(lst)

print(arr)
print(type(arr))
print(arr.dtype)

['10' 'True' 'Hello' '10.6']
<class 'numpy.ndarray'>
<U32


In [48]:
lst = [10, True, "Hello", 10.6, [1, 2, 3]]

arr = np.array(lst)

print(arr)
print(type(arr))
print(arr.dtype)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [54]:
tpl = (10, 20, 30)

arr = np.array(tpl, dtype=np.int32)
print(arr.dtype)

arr = arr.astype(np.int16)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [58]:
st = {1, 2, 3, 4}

arr = np.array(list(st))

print(arr.dtype)

arr = arr.astype(np.int16)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int64
[1 2 3 4]
<class 'numpy.ndarray'>
int16
(4,)
1


In [63]:
dic = {"a": 10, "b": 20, "c": 30}

print(dic.keys())

arr = np.array(list(dic.keys()))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

# ---------------------

print(dic.values())

arr = np.array(list(dic.values()))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

# ---------------------

print(dic.items())

arr = np.array(list(dic.items()))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

dict_keys(['a', 'b', 'c'])
['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
dict_values([10, 20, 30])
[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1
dict_items([('a', 10), ('b', 20), ('c', 30)])
[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2


In [65]:
arr = np.zeros((1, 3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0. 0. 0.]]
<class 'numpy.ndarray'>
float64
(1, 3)
2
3


In [66]:
arr = np.zeros((2, 3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [69]:
import numpy as np

# Create a 2x3 array of zeros
arr = np.zeros((2, 3))

print("Array:\n", arr)
print("Type:", type(arr))
print("Data type:", arr.dtype)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)

# Define another array (arr2)
arr2 = np.array([
    [5, 10, 15],
     [20, 25, 30]
    ])

print("\nArray 2:\n", arr2)
print("Type:", type(arr2))
print("Data type:", arr2.dtype)

# Create a new zero array with the same shape and data type as arr2
arr = np.zeros_like(arr2)

print("\nArray created using zeros_like(arr2):\n", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)


Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Type: <class 'numpy.ndarray'>
Data type: float64
Shape: (2, 3)
Dimensions: 2
Size: 6

Array 2:
 [[ 5 10 15]
 [20 25 30]]
Type: <class 'numpy.ndarray'>
Data type: int64

Array created using zeros_like(arr2):
 [[0 0 0]
 [0 0 0]]
Shape: (2, 3)
Data type: int64


In [70]:
import numpy as np

# Create a 2x3 array of ones
arr = np.ones((2, 3))

print("Array:\n", arr)
print("Type:", type(arr))
print("Data type:", arr.dtype)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)

# Define another array (arr2)
arr2 = np.array([
    [5, 10, 15],
    [20, 25, 30]
])

print("\nArray 2:\n", arr2)
print("Type:", type(arr2))
print("Data type:", arr2.dtype)

# Create a new ones array with the same shape and data type as arr2
arr = np.ones_like(arr2)

print("\nArray created using ones_like(arr2):\n", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)


Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Type: <class 'numpy.ndarray'>
Data type: float64
Shape: (2, 3)
Dimensions: 2
Size: 6

Array 2:
 [[ 5 10 15]
 [20 25 30]]
Type: <class 'numpy.ndarray'>
Data type: int64

Array created using ones_like(arr2):
 [[1 1 1]
 [1 1 1]]
Shape: (2, 3)
Data type: int64


In [73]:
import numpy as np

# Create a 2x3 empty array
arr = np.empty((2, 3))

print("Array:\n", arr)
print("Type:", type(arr))
print("Data type:", arr.dtype)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)

# Define another array (arr2)
arr2 = np.array([
    [5, 10, 15],
    [20, 25, 30]
])

print("\nArray 2:\n", arr2)
print("Type:", type(arr2))
print("Data type:", arr2.dtype)

# Create a new empty array with the same shape and data type as arr2
arr = np.empty_like(arr2)

print("\nArray created using empty_like(arr2):\n", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)


Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Type: <class 'numpy.ndarray'>
Data type: float64
Shape: (2, 3)
Dimensions: 2
Size: 6

Array 2:
 [[ 5 10 15]
 [20 25 30]]
Type: <class 'numpy.ndarray'>
Data type: int64

Array created using empty_like(arr2):
 [[ 5 10 15]
 [20 25 30]]
Shape: (2, 3)
Data type: int64


In [77]:
import numpy as np

# Create a 2x3 empty array (uninitialized values)
arr_empty = np.empty((2, 3))

print("Array created using np.empty():\n", arr_empty)
print("Type:", type(arr_empty))
print("Data type:", arr_empty.dtype)
print("Shape:", arr_empty.shape)
print("Dimensions:", arr_empty.ndim)
print("Size:", arr_empty.size)

# Create a 2x3 full array (all elements filled with 7)
arr_full = np.full((2, 3), 7)

print("\nArray created using np.full():\n", arr_full)
print("Type:", type(arr_full))
print("Data type:", arr_full.dtype)
print("Shape:", arr_full.shape)
print("Dimensions:", arr_full.ndim)
print("Size:", arr_full.size)

# Define another array (arr2)
arr2 = np.array([
    [5, 10, 15],
    [20, 25, 30]
])

print("\nArray 2:\n", arr2)
print("Type:", type(arr2))
print("Data type:", arr2.dtype)

# Create empty and full arrays based on arr2
arr_empty_like = np.empty_like(arr2)
arr_full_like = np.full_like(arr2, np.inf, dtype=float)

print("\nArray created using empty_like(arr2):\n", arr_empty_like)
print("Array created using full_like(arr2, inf):\n", arr_full_like)


Array created using np.empty():
 [[inf inf inf]
 [inf inf inf]]
Type: <class 'numpy.ndarray'>
Data type: float64
Shape: (2, 3)
Dimensions: 2
Size: 6

Array created using np.full():
 [[7 7 7]
 [7 7 7]]
Type: <class 'numpy.ndarray'>
Data type: int64
Shape: (2, 3)
Dimensions: 2
Size: 6

Array 2:
 [[ 5 10 15]
 [20 25 30]]
Type: <class 'numpy.ndarray'>
Data type: int64

Array created using empty_like(arr2):
 [[ 5 10 15]
 [20 25 30]]
Array created using full_like(arr2, inf):
 [[inf inf inf]
 [inf inf inf]]


In [81]:
import numpy as np

# Random float values between 0 and 1
arr_rand = np.random.rand(2, 3)
print("Array created using np.random.rand():\n", arr_rand)
print("Shape:", arr_rand.shape)
print("Data type:", arr_rand.dtype)

# Random integers between 10 and 50
arr_randint = np.random.randint(10, 50, size=(2, 3))
print("\nArray created using np.random.randint():\n", arr_randint)
print("Shape:", arr_randint.shape)
print("Data type:", arr_randint.dtype)

# Random values from a normal (Gaussian) distribution
arr_normal = np.random.randn(2, 3)
print("\nArray created using np.random.randn():\n", arr_normal)
print("Shape:", arr_normal.shape)
print("Data type:", arr_normal.dtype)

# Random values using uniform distribution between -5 and 5
arr_uniform = np.random.uniform(-5, 5, size=(2, 3))
print("\nArray created using np.random.uniform(-5, 5):\n", arr_uniform)
print("Shape:", arr_uniform.shape)
print("Data type:", arr_uniform.dtype)

# Random array with the same shape as another array (arr2)
arr2 = np.array([
    [5, 10, 15],
    [20, 25, 30]
])
arr_random_like = np.random.random_sample(arr2.shape)
print("\nArray created using np.random.random_sample(arr2.shape):\n", arr_random_like)


Array created using np.random.rand():
 [[0.15135137 0.65068291 0.30576982]
 [0.39981347 0.98008375 0.00960441]]
Shape: (2, 3)
Data type: float64

Array created using np.random.randint():
 [[42 33 32]
 [17 17 30]]
Shape: (2, 3)
Data type: int64

Array created using np.random.randn():
 [[-0.47300909  0.36215819  0.52791182]
 [ 0.04191009 -0.52874496 -1.5202601 ]]
Shape: (2, 3)
Data type: float64

Array created using np.random.uniform(-5, 5):
 [[ 2.1234606  -1.81013881  0.95368227]
 [-2.11117069 -3.60105923  4.30282128]]
Shape: (2, 3)
Data type: float64

Array created using np.random.random_sample(arr2.shape):
 [[0.98839381 0.00761641 0.94449753]
 [0.06377011 0.95815345 0.5123982 ]]


In [91]:
import numpy as np

# Using np.arange()
arr_arange = np.arange(1, 10, 1)   # start=0, stop=10, step=2
print("Array created using np.arange(0, 10, 2):", arr_arange)
print("Type:", type(arr_arange))
print("Data type:", arr_arange.dtype)
print("Shape:", arr_arange.shape)

print()

matrix = arr_arange.reshape(3, 3)
print("Array created using np.arange(0, 10, 2):\n", matrix)
print("Type:", type(matrix))
print("Data type:", matrix.dtype)
print("Shape:", matrix.shape)

Array created using np.arange(0, 10, 2): [1 2 3 4 5 6 7 8 9]
Type: <class 'numpy.ndarray'>
Data type: int64
Shape: (9,)

Array created using np.arange(0, 10, 2):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type: <class 'numpy.ndarray'>
Data type: int64
Shape: (3, 3)


In [92]:
import numpy as np

arr_linspace = np.linspace(0, 1, 5)  # start=0, stop=1, 5 equally spaced values

print("\nArray created using np.linspace(0, 1, 5):", arr_linspace)
print("Type:", type(arr_linspace))
print("Data type:", arr_linspace.dtype)
print("Shape:", arr_linspace.shape)




Array created using np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
Type: <class 'numpy.ndarray'>
Data type: float64
Shape: (5,)


In [95]:
arr_logspace = np.logspace(1, 3, 5)  # 10^1 to 10^3, 5 values on log scale
print("\nArray created using np.logspace(1, 3, 5):\n", arr_logspace)
print("Type:", type(arr_logspace))
print("Data type:", arr_logspace.dtype)
print("Shape:", arr_logspace.shape)


Array created using np.logspace(1, 3, 5):
 [  10.           31.6227766   100.          316.22776602 1000.        ]
Type: <class 'numpy.ndarray'>
Data type: float64
Shape: (5,)


In [96]:
arr_logspace = np.logspace(1, 3, 5, base=2)  # 10^1 to 10^3, 5 values on log scale
print("\nArray created using np.logspace(1, 3, 5):\n", arr_logspace)
print("Type:", type(arr_logspace))
print("Data type:", arr_logspace.dtype)
print("Shape:", arr_logspace.shape)


Array created using np.logspace(1, 3, 5):
 [2.         2.82842712 4.         5.65685425 8.        ]
Type: <class 'numpy.ndarray'>
Data type: float64
Shape: (5,)


In [98]:
import numpy as np

# Create a diagonal matrix directly from a list or array
arr = np.diag([1, 2, 3, 4])
print("Diagonal matrix using np.diag([1,2,3,4]):\n", arr)

# Create a diagonal matrix with an offset diagonal (+1 = above, -1 = below)
arr_offset = np.diag([10, 20, 30], k=1)
print("\nDiagonal matrix with offset (k=1):\n", arr_offset)

# Create a diagonal matrix with an offset diagonal (+1 = above, -1 = below)
arr_offset = np.diag([10, 20, 30], k=-1)
print("\nDiagonal matrix with offset (k=1):\n", arr_offset)

Diagonal matrix using np.diag([1,2,3,4]):
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Diagonal matrix with offset (k=1):
 [[ 0 10  0  0]
 [ 0  0 20  0]
 [ 0  0  0 30]
 [ 0  0  0  0]]

Diagonal matrix with offset (k=1):
 [[ 0  0  0  0]
 [10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]]


In [100]:
import numpy as np

# Basic identity matrix of size 3x3
I1 = np.eye(3)
print("Identity matrix (3x3):\n", I1)

# Identity matrix with diagonal shifted up by 1 (k=1)
I2 = np.eye(4, k=1)
print("\nIdentity matrix with upper diagonal (k=1):\n", I2)

# Non-square identity-like matrix (rows ≠ columns)
I3 = np.eye(3, 5)
print("\nIdentity-like matrix (3x5):\n", I3)

# Identity matrix with integer type
I4 = np.eye(4, dtype=int)
print("\nIdentity matrix with integer data type:\n", I4)


Identity matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Identity matrix with upper diagonal (k=1):
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

Identity-like matrix (3x5):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

Identity matrix with integer data type:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [102]:
import numpy as np

# Create a 2D array
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print("Original Array:\n", arr)

# Accessing individual elements (Indexing)
print("\nElement at 1st row, 2nd column:", arr[0, 1])  # 20
print("Element at 3rd row, 4th column:", arr[2, 3])   # 120

# Accessing entire rows or columns
print("\nFirst row:", arr[0])       # [10 20 30 40]
print("Second column:", arr[:, 1])  # [ 20  60 100]

# Slicing rows and columns
print("\nFirst two rows:\n", arr[0:2])
print("Last two columns:\n", arr[:, 2:])

# Step slicing
print("\nEvery 2nd element from first row:", arr[0, ::2])  # [10 30]
print("Every 2nd row:\n", arr[::2])                       # rows 0 and 2

# Negative indexing
print("\nLast row:", arr[-1])         # [90 100 110 120]
print("Last element of last row:", arr[-1, -1])  # 120

# Modifying specific elements
arr[1, 2] = 999
print("\nModified element at (1,2):\n", arr)

# Slicing and modifying multiple elements
arr[0:2, 1:3] = 0
print("\nAfter modifying subarray [0:2, 1:3]:\n", arr)

# Fancy indexing (selecting specific rows/columns)
selected_rows = arr[[0, 2]]
print("\nSelected rows (0 and 2):\n", selected_rows)

selected_cols = arr[:, [0, 3]]
print("\nSelected columns (0 and 3):\n", selected_cols)


Original Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Element at 1st row, 2nd column: 20
Element at 3rd row, 4th column: 120

First row: [10 20 30 40]
Second column: [ 20  60 100]

First two rows:
 [[10 20 30 40]
 [50 60 70 80]]
Last two columns:
 [[ 30  40]
 [ 70  80]
 [110 120]]

Every 2nd element from first row: [10 30]
Every 2nd row:
 [[ 10  20  30  40]
 [ 90 100 110 120]]

Last row: [ 90 100 110 120]
Last element of last row: 120

Modified element at (1,2):
 [[ 10  20  30  40]
 [ 50  60 999  80]
 [ 90 100 110 120]]

After modifying subarray [0:2, 1:3]:
 [[ 10   0   0  40]
 [ 50   0   0  80]
 [ 90 100 110 120]]

Selected rows (0 and 2):
 [[ 10   0   0  40]
 [ 90 100 110 120]]

Selected columns (0 and 3):
 [[ 10  40]
 [ 50  80]
 [ 90 120]]


In [105]:
import numpy as np

# Base array
A = np.arange(1, 13).reshape(3, 4)
# A =
# [[ 1,  2,  3,  4],
#  [ 5,  6,  7,  8],
#  [ 9, 10, 11, 12]]

print("A:\n", A)

# 1) Fancy (integer) indexing: pick arbitrary rows/cols
rows = [0, 2]
cols = [1, 3]
print("\nRows 0 & 2:\n", A[rows])                 # shape (2, 4)
print("Cols 1 & 3 (all rows):\n", A[:, cols])     # shape (3, 2)

# 2) Element-wise pairs with two index arrays (same shape)
ri = np.array([0, 1, 2])
ci = np.array([0, 1, 2])
print("\nDiagonal via matching index arrays:", A[ri, ci])  # [1, 6, 11]

# 3) Boolean indexing (masking)
mask = A % 2 == 0
print("\nAll even elements (1D result):", A[mask])  # flattens selected values
B = A.copy()
B[B > 6] = -1
print("Replace >6 with -1:\n", B)

# 4) Mixing slices + fancy indexing (fancy kills view -> makes a copy)
print("\nFirst two rows, cols [0, 2]:\n", A[:2, [0, 2]])


A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Rows 0 & 2:
 [[ 1  2  3  4]
 [ 9 10 11 12]]
Cols 1 & 3 (all rows):
 [[ 2  4]
 [ 6  8]
 [10 12]]

Diagonal via matching index arrays: [ 1  6 11]

All even elements (1D result): [ 2  4  6  8 10 12]
Replace >6 with -1:
 [[ 1  2  3  4]
 [ 5  6 -1 -1]
 [-1 -1 -1 -1]]

First two rows, cols [0, 2]:
 [[1 3]
 [5 7]]


In [108]:
arr = np.array([[10, 20, 30], [100, 200, 300]])

for i in np.nditer(arr):
    print(i)

10
20
30
100
200
300


You have a list of temperatures recorded in Celsius. Your task is to:

Create a NumPy array from the given list.

Convert all temperatures from Celsius to Fahrenheit. The formula is F = C* 1.8 + 32.

Print the new Fahrenheit array.


In [109]:
import numpy as np

celsius = [0, 20, 37, 100, -10, 15]

arr_celsius = np.array(celsius)
print("Celsius array:", arr_celsius)

arr_fahrenheit = arr_celsius * 1.8 + 32

print("Fahrenheit array:", arr_fahrenheit)


Celsius array: [  0  20  37 100 -10  15]
Fahrenheit array: [ 32.   68.   98.6 212.   14.   59. ]


  You have a Python list containing the lap times (in seconds) for an athlete.

Task:

Convert the list into a NumPy array.

Print the array's shape, size, and data type.

The athlete wants to see their times in minutes. Create a new array by dividing all the lap times by 60.

Print the new array of lap times in minutes.


In [110]:
import numpy as np

lap_times = [75, 80, 90, 88, 95, 100]

arr_seconds = np.array(lap_times)
print("Lap times array (in seconds):", arr_seconds)

print("Shape:", arr_seconds.shape)
print("Size:", arr_seconds.size)
print("Data type:", arr_seconds.dtype)

arr_minutes = arr_seconds / 60

print("\nLap times (in minutes):", arr_minutes)


Lap times array (in seconds): [ 75  80  90  88  95 100]
Shape: (6,)
Size: 6
Data type: int64

Lap times (in minutes): [1.25       1.33333333 1.5        1.46666667 1.58333333 1.66666667]
