In [ ]:
import numpy as np

# Create a random integer array with 10 samples (rows) and 5 features (columns)
arr = np.random.randint(1, 100, size=(10, 5))

print("Original Array (10x5):")
print(arr)
print("Shape:", arr.shape)
print("-" * 50)

Original Array (10x5):
[[17 30 96 13 92]
 [89 92 38 73 99]
 [28 65 32 16 89]
 [23 46 58 94 44]
 [91 30 51  5 80]
 [59 22  3 23 14]
 [ 5 41 58 36  6]
 [32  7 94 36 29]
 [26 89 22 47 97]
 [85 63 35 95 52]]
Shape: (10, 5)
--------------------------------------------------


In [ ]:
# Reshape the array to 5 rows and 10 columns
reshaped = arr.reshape(5, 10)

print("Reshaped Array (5x10):")
print(reshaped)
print("Shape:", reshaped.shape)
print("Dimensions:", reshaped.ndim)
print("-" * 50)

Reshaped Array (5x10):
[[17 30 96 13 92 89 92 38 73 99]
 [28 65 32 16 89 23 46 58 94 44]
 [91 30 51  5 80 59 22  3 23 14]
 [ 5 41 58 36  6 32  7 94 36 29]
 [26 89 22 47 97 85 63 35 95 52]]
Shape: (5, 10)
Dimensions: 2
--------------------------------------------------


In [ ]:
# Flatten the reshaped array into a 1D array (Row-major order)
flattened = reshaped.flatten()

print("Flattened Array (Row-major order):")
print(flattened)
print("Shape:", flattened.shape)
print("Dimensions:", flattened.ndim)
print("-" * 50)

Flattened Array (Row-major order):
[17 30 96 13 92 89 92 38 73 99 28 65 32 16 89 23 46 58 94 44 91 30 51  5
 80 59 22  3 23 14  5 41 58 36  6 32  7 94 36 29 26 89 22 47 97 85 63 35
 95 52]
Shape: (50,)
Dimensions: 1
--------------------------------------------------


In [ ]:
# Flatten the reshaped array in Column-major order
column_flattened = np.ravel(reshaped, order='F')

print("Flattened Array (Column-major order):")
print(column_flattened)
print("Shape:", column_flattened.shape)
print("Dimensions:", column_flattened.ndim)

Flattened Array (Column-major order):
[17 28 91  5 26 30 65 30 41 89 96 32 51 58 22 13 16  5 36 47 92 89 80  6
 97 89 23 59 32 85 92 46 22  7 63 38 58  3 94 35 73 94 23 36 95 99 44 14
 29 52]
Shape: (50,)
Dimensions: 1


In [ ]:
import numpy as np

# Create two random integer arrays of shape (2, 3)
a = np.random.randint(1, 10, size=(2, 3))
b = np.random.randint(20, 30, size=(2, 3))

print("Array A:")
print(a)
print("-" * 30)
print("Array B:")
print(b)
print("-" * 30)

Array A:
[[9 9 8]
 [7 5 1]]
------------------------------
Array B:
[[25 20 28]
 [28 25 29]]
------------------------------


In [ ]:
# Row-wise concatenate possible if both matrix have same column
# Column-wise concatenate possible if both matrix have same row

# Concatenate arrays along axis 0 (row-wise)
con = np.concatenate((a, b), axis=0)

print("Concatenated Array (axis=0):")
print(con)
print("Shape:", con.shape)


Concatenated Array (axis=0):
[[ 9  9  8]
 [ 7  5  1]
 [25 20 28]
 [28 25 29]]
Shape: (4, 3)


In [ ]:
# Concatenate arrays along axis 1 (column-wise)
con = np.concatenate((a, b), axis=1)

print("Concatenated Array (axis=1):")
print(con)
print("Shape:", con.shape)


Concatenated Array (axis=1):
[[ 9  9  8 25 20 28]
 [ 7  5  1 28 25 29]]
Shape: (2, 6)


In [ ]:
import numpy as np

# Create a 2x3 matrix
mat = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# Transpose the matrix (rows become columns and vice versa)
transpose = mat.T

print("Original Matrix (2x3):")
print(mat)
print("Shape:", mat.shape)
print("-" * 40)

print("Transposed Matrix (3x2):")
print(transpose)
print("Shape:", transpose.shape)
print("-" * 40)

Original Matrix (2x3):
[[10 20 30]
 [40 50 60]]
Shape: (2, 3)
----------------------------------------
Transposed Matrix (3x2):
[[10 40]
 [20 50]
 [30 60]]
Shape: (3, 2)
----------------------------------------


In [ ]:
import numpy as np

# Create a 1D array with 10 random integers
a = np.random.randint(1, 10, size=(10,))
print("Original Array:")
print(a)
print("-" * 40)

# Split the array into 3 nearly equal parts (uneven split allowed)
split1 = np.array_split(a, 3)
print("Split into 3 parts using np.array_split():")
for i, part in enumerate(split1, start=1):
    print(f"Part {i}:", part)
print("-" * 40)

# Split the array into 2 equal parts (must divide evenly)
split2 = np.split(a, 2)
print("Split into 2 equal parts using np.split():")
for i, part in enumerate(split2, start=1):
    print(f"Part {i}:", part)


Original Array:
[7 5 8 1 4 2 2 2 7 9]
----------------------------------------
Split into 3 parts using np.array_split():
Part 1: [7 5 8 1]
Part 2: [4 2 2]
Part 3: [2 7 9]
----------------------------------------
Split into 2 equal parts using np.split():
Part 1: [7 5 8 1 4]
Part 2: [2 2 2 7 9]


In [ ]:
import numpy as np

# Define two 1D arrays
a = np.array([10, 20, 30, 40, 50])
b = np.array([100, 200, 300, 400, 500])

print("Array A:", a)
print("Array B:", b)
print("-" * 60)

# Element-wise addition
addition = a + b
print("Addition (a + b):", addition)

# Using np.add()
add = np.add(a, b)
print("Addition using np.add():", add)
print("-" * 60)

# Subtraction
subtraction = a - b
print("Subtraction (a - b):", subtraction)

# Multiplication
multiplication = a * b
print("Multiplication (a * b):", multiplication)

# Division
division = a / b
print("Division (a / b):", division)

# Remainder
remainder = a % b
print("Remainder (a % b):", remainder)
print("-" * 60)

# Trigonometric functions (in radians)
sin_values = np.sin(a)
cos_values = np.cos(a)
print("Sine values:", sin_values)
print("Cosine values:", cos_values)
print("-" * 60)

# Logarithmic and Exponential functions
log_values = np.log(a)
exp_values = np.exp(a)
print("Natural Logarithm (log):", log_values)
print("Exponential (exp):", exp_values)
print("-" * 60)

# Angle conversions
deg_to_rad = np.deg2rad(a)
rad_to_deg = np.rad2deg(a)
print("Degrees to Radians:", deg_to_rad)
print("Radians to Degrees:", rad_to_deg)


Array A: [10 20 30 40 50]
Array B: [100 200 300 400 500]
------------------------------------------------------------
Addition (a + b): [110 220 330 440 550]
Addition using np.add(): [110 220 330 440 550]
------------------------------------------------------------
Subtraction (a - b): [ -90 -180 -270 -360 -450]
Multiplication (a * b): [ 1000  4000  9000 16000 25000]
Division (a / b): [0.1 0.1 0.1 0.1 0.1]
Remainder (a % b): [10 20 30 40 50]
------------------------------------------------------------
Sine values: [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
Cosine values: [-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
------------------------------------------------------------
Natural Logarithm (log): [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
Exponential (exp): [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
------------------------------------------------------------
Degrees to Radians: [0.17453293 0.349065

In [ ]:
import numpy as np

a = np.array([1, 2, 3])      # Shape: (3,)
b = 2                         # Scalar (single value)

result = a ** b

print("Array a:", a)
print("Scalar b:", b)
print("Result:", result)

Array a: [1 2 3]
Scalar b: 2
Result: [1 4 9]


In [ ]:
import numpy as np

# a is a matrix
a = np.array([[1, 2, 3],
              [4, 5, 6]])      # Shape: (2, 3)

# b is a vector
b = np.array([10, 20, 30])     # Shape: (3,)

result = a + b

print("Array a:\n", a)
print("Array b:", b)
print("Result:\n", result)


Array a:
 [[1 2 3]
 [4 5 6]]
Array b: [10 20 30]
Result:
 [[11 22 33]
 [14 25 36]]


In [ ]:
import numpy as np

a = np.array([[1], [2], [3]])   # Shape: (3, 1)
b = np.array([10, 20, 30])      # Shape: (3,)

result = a + b

print("Array a:\n", a)
print("Array b:", b)
print("Result:\n", result)


Array a:
 [[1]
 [2]
 [3]]
Array b: [10 20 30]
Result:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([20, 20, 25, 40, 60])

print("Array A:", a)
print("Array B:", b)
print("-" * 50)

print("A == B:", a == b)   # Equal
print("A != B:", a != b)   # Not equal
print("A > B :", a > b)    # Greater than
print("A < B :", a < b)    # Less than
print("A >= B:", a >= b)   # Greater or equal
print("A <= B:", a <= b)   # Less or equal


Array A: [10 20 30 40 50]
Array B: [20 20 25 40 60]
--------------------------------------------------
A == B: [False  True False  True False]
A != B: [ True False  True False  True]
A > B : [False False  True False False]
A < B : [ True False False False  True]
A >= B: [False  True  True  True False]
A <= B: [ True  True False  True  True]


In [ ]:
import numpy as np

a = np.array([True, True, True])
b = np.array([True, False, True])

print("np.all(a):", np.all(a))
print("np.all(b):", np.all(b))


np.all(a): True
np.all(b): False


In [ ]:
import numpy as np

a = np.array([False, False, True])
b = np.array([False, False, False])

print("np.any(a):", np.any(a))
print("np.any(b):", np.any(b))


np.any(a): True
np.any(b): False


In [ ]:
import numpy as np

arr = np.array([40, 10, 20, 60, 50])

print("Original Array:")
print(arr)

sorted_arr = np.sort(arr)  # returns a sorted copy

print("Sorted Copy:")
print(sorted_arr)

print("After sorting (original remains same):")
print(arr)


Original Array:
[40 10 20 60 50]
Sorted Copy:
[10 20 40 50 60]
After sorting (original remains same):
[40 10 20 60 50]


In [ ]:
import numpy as np

arr = np.array([40, 10, 20, 60, 50])

print("Original Array:")
print(arr)

arr.sort()   # modifies the original array (in-place)

print("After In-Place Sorting:")
print(arr)


Original Array:
[40 10 20 60 50]
After In-Place Sorting:
[10 20 40 50 60]


In [ ]:
import numpy as np

a = np.array([30, 10, 50, 20])

# Copy sort
b = np.sort(a)
print("Sorted Copy (b):", b)
print("Original (a):", a)

# In-place sort
a.sort()
print("After In-Place Sort (a):", a)


Sorted Copy (b): [10 20 30 50]
Original (a): [30 10 50 20]
After In-Place Sort (a): [10 20 30 50]


In [ ]:
arr = np.array([[3, 1, 9],
                [9, 7, 8]])

# Sort along each row (axis=1)
row_sorted = np.sort(arr, axis=1)
print("Row-wise Sorted:\n", row_sorted)

# Sort along each column (axis=0)
col_sorted = np.sort(arr, axis=0)
print("Column-wise Sorted:\n", col_sorted)


Row-wise Sorted:
 [[1 3 9]
 [7 8 9]]
Column-wise Sorted:
 [[3 1 8]
 [9 7 9]]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Find indices where elements > 25
indices = np.where(arr > 25)

print("Array:", arr)
print("Indices where arr > 25:", indices)
print("Values:", arr[indices])


Array: [10 20 30 40 50]
Indices where arr > 25: (array([2, 3, 4]),)
Values: [30 40 50]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Replace elements greater than 25 with their value, otherwise 0
result = np.where(arr > 25, arr, 0)

print("Original Array:", arr)
print("Result (arr > 25 replaced, else 0):", result)



Original Array: [10 20 30 40 50]
Result (arr > 25 replaced, else 0): [ 0  0 30 40 50]


In [ ]:
import numpy as np

# Create a 2D array
arr = np.array([
    [10, 50, 30],
    [40, 20, 60]
])

# Get indices where condition is True
indices = np.where(arr > 25)

print("Array:\n", arr)
print("Indices where arr > 25:", indices)
print("Values at those indices:", arr[indices])
print("-" * 50)

# Conditional replacement: keep values > 25, else replace with 0
result = np.where(arr > 25, arr, 0)

print("Original Array:\n", arr)
print("Result (arr > 25 → keep value, else 0):\n", result)


Array:
 [[10 50 30]
 [40 20 60]]
Indices where arr > 25: (array([0, 0, 1, 1]), array([1, 2, 0, 2]))
Values at those indices: [50 30 40 60]
--------------------------------------------------
Original Array:
 [[10 50 30]
 [40 20 60]]
Result (arr > 25 → keep value, else 0):
 [[ 0 50 30]
 [40  0 60]]


In [ ]:
import numpy as np

arr = np.array([
    [10, 50, 30],
    [40, 20, 60]
])

# Maximum and Minimum values
max_value = np.max(arr)
min_value = np.min(arr)

print("Array:\n", arr)
print("Maximum value:", max_value)
print("Minimum value:", min_value)


Array:
 [[10 50 30]
 [40 20 60]]
Maximum value: 60
Minimum value: 10


In [ ]:
# Get index (in flattened form)
max_index = np.argmax(arr)
min_index = np.argmin(arr)

print("Index of Max value:", max_index)
print("Index of Min value:", min_index)


Index of Max value: 5
Index of Min value: 0


In [ ]:
# Row-wise max (axis=1 → across columns)
row_max = np.max(arr, axis=1)

# Column-wise max (axis=0 → across rows)
col_max = np.max(arr, axis=0)

print("Row-wise max:", row_max)
print("Column-wise max:", col_max)


Row-wise max: [50 60]
Column-wise max: [40 50 60]


In [ ]:
arr = np.array([10, 20, 20, 30, 40, 20])

count_20 = np.count_nonzero(arr == 20)
print("Count of 20:", count_20)

Count of 20: 3


In [ ]:
# Count how many elements are greater than 25
count_greater_25 = np.count_nonzero(arr > 25)
print("Count of elements > 25:", count_greater_25)


Count of elements > 25: 2


In [ ]:
arr = np.array([10, 50, 30, 70, 20])

mask = arr > 30
print("Mask:", mask)
print("Values > 30:", arr[mask])
print("Count:", np.count_nonzero(mask))


Mask: [False  True False  True False]
Values > 30: [50 70]
Count: 2


In [ ]:
import numpy as np

arr = np.array([10, 20, 20, 30, 40, 10, 50, 30])

unique_values = np.unique(arr)

print("Original Array:", arr)
print("Unique Values:", unique_values)

Original Array: [10 20 20 30 40 10 50 30]
Unique Values: [10 20 30 40 50]
Unique Values: [10 20 30 40 50]
Counts: [2 2 2 1 1]


In [ ]:
unique_values, counts = np.unique(arr, return_counts=True)

print("Unique Values:", unique_values)
print("Counts:", counts)

Unique Values: [10 20 30 40 50]
Counts: [2 2 2 1 1]


In [ ]:
unique_values, indices = np.unique(arr, return_index=True)

print("Unique Values:", unique_values)
print("First Occurrence Indices:", indices)


Unique Values: [10 20 30 40 50]
First Occurrence Indices: [0 1 3 4 6]


In [ ]:
import numpy as np

data = np.genfromtxt('./sample_data/students_marks.csv', delimiter=',', skip_header=1)

print(data)


[[ 54.  76.  80.]
 [100.  48.  97.]
 [ 61.  94.  50.]
 [ 64.  46.  43.]
 [ 67.  48.  68.]
 [ 94.  73.  73.]
 [ 53.  51.  68.]
 [ 51.  62.  79.]
 [ 82.  82.  49.]
 [ 81.  50.  44.]
 [ 69.  53.  40.]
 [ 44.  97.  87.]
 [ 92.  57.  84.]
 [ 86.  91.  97.]
 [ 61.  87.  86.]
 [ 43.  62.  68.]
 [ 97.  96.  70.]
 [ 75.  95.  62.]
 [ 89.  53.  50.]
 [ 81.  71.  61.]]


In [ ]:
# Select the Math column (first column → index 0)
math_marks = data[:, 0]

print("Math Marks:", math_marks)

max_math = np.max(math_marks)
print("Maximum Marks:", max_math)

min_math = np.min(math_marks)
print("Minimum Marks:", min_math)

sum_math = np.sum(math_marks)
print("Sum of Marks:", sum_math)

# Count: number of students (number of values)
count_math = np.size(math_marks)
print("Number of Students:", count_math)

# Mean (Average): total sum ÷ number of values
mean_math = np.mean(math_marks)
print("Mean (Average):", mean_math)

# Median: the middle value when all marks are sorted
# Half of the marks are below and half are above this value.
median_math = np.median(math_marks)
print("Median:", median_math)

# Standard Deviation (σ):
# It measures how much the marks deviate from the average.
# Small std = marks are close to the mean.
# Large std = marks are widely spread out.
std_math = np.std(math_marks)
print("Standard Deviation:", std_math)

# Variance:
# It’s the square of standard deviation.
# Also measures how spread the data is, but in squared units.
var_math = np.var(math_marks)
print("Variance:", var_math)

Math Marks: [ 54. 100.  61.  64.  67.  94.  53.  51.  82.  81.  69.  44.  92.  86.
  61.  43.  97.  75.  89.  81.]
Maximum Marks: 100.0
Minimum Marks: 43.0
Sum of Marks: 1444.0
Number of Students: 20
Mean (Average): 72.2
Median: 72.0
Standard Deviation: 17.52027397046062
Variance: 306.96


In [ ]:
import numpy as np

math = np.array([60, 70, 80, 90, 100])
study = np.array([5, 7, 10, 12, 15])

# Calculate correlation coefficient matrix
correlation_matrix = np.corrcoef(math, study)

print("Correlation Coefficient Matrix:")
print(correlation_matrix)


Correlation Coefficient Matrix:
[[1.         0.99760861]
 [0.99760861 1.        ]]


In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Addition
C = A + B

# Subtraction
D = A - B

print("A + B =\n", C)
print("A - B =\n", D)


A + B =
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
A - B =
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [ ]:
E = np.dot(A, B.T)   # A × Bᵀ
print("Matrix Multiplication:\n", E)


Matrix Multiplication:
 [[ 46  28  10]
 [118  73  28]
 [190 118  46]]
