### Student Marks Analyzer

You are helping a teacher check exam results.
 Create a NumPy array with 10 random integers between 0 and 100 (student scores).

 Find:
 - the highest score
 - the lowest score
 - the average score

 Hint: use np.random.randint(), arr.max(), arr.min(), arr.mean()

In [13]:
import numpy as np

scores = np.random.randint(0, 101, size = 10)

print("Student Scores: ", scores)

highest_score = scores.max()
lowest_score = scores.min()
average_score = scores.mean()

print("Highest Score: ", highest_score)
print("Lowest Score: ", lowest_score)
print("Average Score: ", average_score)

Student Scores:  [18 10 43 36 20 64 82 12 12 95]
Highest Score:  95
Lowest Score:  10
Average Score:  39.2


### Warehouse Weights

A warehouse stores item weights (in kg):
 arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])

 Find and print:
 - all items heavier than 50 kg
 - the sorted weights
 - the index of the heaviest item

 Hint: use arr[arr > 50], np.sort(arr), arr.argmax()

In [14]:
arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])

heavier_items = arr[arr > 50]
sorted_weights = np.sort(arr)
heaviest_item_index = arr.argmax()

print("All items heavier than 50 kg: ", heavier_items)
print("Sorted weights: ", sorted_weights)
print("Index of the heaviest item: ", heaviest_item_index)

All items heavier than 50 kg:  [60 55 90 75]
Sorted weights:  [30 40 45 50 55 60 75 90]
Index of the heaviest item:  4


### Temperature Report

A weather station collects temperatures (°C) from 4 zones.
 Generate random integers between 20 and 40 for a 4×4 grid.

 Then find:
 - the average temperature of each zone (row)
 - the highest temperature in the grid
 - replace all temperatures above 35 with 35

In [15]:
temps = np.random.randint(20, 41, size=(4, 4))

print("Temperature Grid (°C):\n", temps)

average_temps = np.mean(temps, axis=1)
highest_temp = np.max(temps)
temps[temps > 35] = 35

print("\nAverage Temperatures (°C):", average_temps)
print("Highest Temperature (°C):", highest_temp)
print("\nTemperature Grid after Replacement (°C):\n", temps)


Temperature Grid (°C):
 [[35 35 37 27]
 [29 40 24 39]
 [30 24 38 28]
 [21 27 24 32]]

Average Temperatures (°C): [33.5 33.  30.  26. ]
Highest Temperature (°C): 40

Temperature Grid after Replacement (°C):
 [[35 35 35 27]
 [29 35 24 35]
 [30 24 35 28]
 [21 27 24 32]]


### Traffic Data
A city records the number of cars passing 5 intersections in 3 time slots (morning, afternoon, night).
 Create a 3×5 array of random integers between 0 and 50.

 Then find:
 - total cars per intersection (sum by column)
 - total cars per time slot (sum by row)

In [16]:
traffic = np.random.randint(0, 51, size=(3, 5))

print("Traffic Data:\n", traffic)

total_cars_per_intersection = np.sum(traffic, axis=0)
total_cars_per_time_slot = np.sum(traffic, axis=1)

print("\nTotal Cars per Intersection:", total_cars_per_intersection)
print("Total Cars per Time Slot:", total_cars_per_time_slot)

Traffic Data:
 [[21 26 35 34 18]
 [48 26 27 12 25]
 [18 23 20 30 31]]

Total Cars per Intersection: [87 75 82 76 74]
Total Cars per Time Slot: [134 138 122]


### Fruit Store Stock
You sell fruits in your store. Stock levels (kg) for 5 days are:
 stock = np.array([12, 15, 9, 20, 18])

 A new delivery adds 5 kg to each stock.
 Then 10% of all fruits get spoiled.

 Find the final stock levels.

 Hint: use broadcasting and simple math.


In [20]:
stock = np.array([12, 15, 9, 20, 18], dtype=float)

new_delivery = 5
stock += new_delivery

print("New Delivery (kg):", new_delivery)
print("Updated Stock Levels (kg):", stock)

spoiled_fruits = stock * 0.1
stock -= spoiled_fruits

print("Final Stock Levels (kg):", stock)


New Delivery (kg): 5
Updated Stock Levels (kg): [17. 20. 14. 25. 23.]
Final Stock Levels (kg): [15.3 18.  12.6 22.5 20.7]


### Student Report Analyzer
You are given this data:

 import pandas as pd

 data = {
 	'Name': ['Rahim', 'Karim', 'Selina', 'Babul', 'Mitu'],
 	'Math': [88, 75, 95, 60, 80],
 	'English': [78, 85, 90, 70, 88],
 	'Science': [92, 70, 85, 65, 90]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Display only the first 3 rows.
 2. Print the column names and index values.

In [24]:
import pandas as pd

data = {
    'Name': ['Rahim', 'Karim', 'Selina', 'Babul', 'Mitu'],
    'Math': [88, 75, 95, 60, 80],
    'English': [78, 85, 90, 70, 88],
    'Science': [92, 70, 85, 65, 90]
}

df = pd.DataFrame(data)

print("First 3 rows of the DataFrame:")
print(df.head(3))

print("\nColumn Names:", df.columns.tolist())
print("Index Values:", df.index.tolist())


First 3 rows of the DataFrame:
     Name  Math  English  Science
0   Rahim    88       78       92
1   Karim    75       85       70
2  Selina    95       90       85

Column Names: ['Name', 'Math', 'English', 'Science']
Index Values: [0, 1, 2, 3, 4]


### Shop Sales Data
You run a small electronics shop. The data is stored like this:

 data = {
 	'Product': ['Phone', 'Laptop', 'Tablet', 'Monitor', 'Mouse'],
 	'Price': [700, 1200, 300, 250, 50],
 	'Units_Sold': [10, 5, 8, 6, 20]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Display only the 'Product' and 'Price' columns.
 2. Access the 3rd row using both iloc and loc.
 3. Show the top 3 products with the highest revenue.

In [25]:
data = {
    'Product': ['Phone', 'Laptop', 'Tablet', 'Monitor', 'Mouse'],
    'Price': [700, 1200, 300, 250, 50],
    'Units_Sold': [10, 5, 8, 6, 20]
}

df = pd.DataFrame(data)

# Display only 'Product' and 'Price' columns
print("Product and Price columns:")
print(df[['Product', 'Price']])

# Access the 3rd row using both iloc and loc
print("\n3rd row using iloc:")
print(df.iloc[2])   # index-based access

print("\n3rd row using loc:")
print(df.loc[2])    # label-based access (same as iloc here, since index = 0,1,2,...)

# Show the top 3 products with the highest revenue
df['Revenue'] = df['Price'] * df['Units_Sold']
top3 = df.sort_values(by='Revenue', ascending=False).head(3)

print("\nTop 3 products with highest revenue:")
print(top3[['Product', 'Revenue']])


Product and Price columns:
   Product  Price
0    Phone    700
1   Laptop   1200
2   Tablet    300
3  Monitor    250
4    Mouse     50

3rd row using iloc:
Product       Tablet
Price            300
Units_Sold         8
Name: 2, dtype: object

3rd row using loc:
Product       Tablet
Price            300
Units_Sold         8
Name: 2, dtype: object

Top 3 products with highest revenue:
  Product  Revenue
0   Phone     7000
1  Laptop     6000
2  Tablet     2400


### Attendance Tracker
Here’s an attendance sheet:

 data = {
 	'Student': ['Amin', 'Tina', 'Rafi', 'Nadia', 'Sabbir'],
 	'Days_Present': [20, 18, 22, 15, 25],
 	'Days_Absent': [2, 4, 1, 7, 0]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Make 'Student' the index column.
 2. Drop the 'Days_Absent' column.


In [31]:
import pandas as pd

data = {
    'Student': ['Amin', 'Tina', 'Rafi', 'Nadia', 'Sabbir'],
    'Days_Present': [20, 18, 22, 15, 25],
    'Days_Absent': [2, 4, 1, 7, 0]
}

# Create DataFrame
df = pd.DataFrame(data)

# Show the original DataFrame
print("Original DataFrame:")
print(df)

# Make 'Student' the index column
df.set_index('Student', inplace=True)

# Drop the 'Days_Absent' column
df.drop('Days_Absent', axis=1, inplace=True)

# Display the final DataFrame
print("\nFinal Attendance DataFrame:")
print(df)


Original DataFrame:
  Student  Days_Present  Days_Absent
0    Amin            20            2
1    Tina            18            4
2    Rafi            22            1
3   Nadia            15            7
4  Sabbir            25            0

Final Attendance DataFrame:
         Days_Present
Student              
Amin               20
Tina               18
Rafi               22
Nadia              15
Sabbir             25


### Filtering Employee Data
Employee record:

 data = {
 	'Name': ['Rafiq', 'Nadia', 'Tuhin', 'Rima', 'Faruk'],
 	'Department': ['HR', 'IT', 'IT', 'Sales', 'Sales'],
 	'Salary': [40000, 55000, 52000, 45000, 47000],
 	'Experience': [2, 5, 4, 3, 6]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Show employees with Salary > 45000.
 2. Show employees from the IT department only.
 3. Show employees with Salary > 45000 and Experience > 3.
 4. Sort the employees by Experience (ascending).

In [32]:
import pandas as pd

# Employee data
data = {
    'Name': ['Rafiq', 'Nadia', 'Tuhin', 'Rima', 'Faruk'],
    'Department': ['HR', 'IT', 'IT', 'Sales', 'Sales'],
    'Salary': [40000, 55000, 52000, 45000, 47000],
    'Experience': [2, 5, 4, 3, 6]
}

df = pd.DataFrame(data)

print("Original Employee Data:")
print(df)

# Employees with Salary > 45000
print("\nEmployees with Salary > 45000:")
print(df[df['Salary'] > 45000])

# Employees from the IT department only
print("\nEmployees from IT Department:")
print(df[df['Department'] == 'IT'])

# Employees with Salary > 45000 and Experience > 3
print("\nEmployees with Salary > 45000 and Experience > 3:")
print(df[(df['Salary'] > 45000) & (df['Experience'] > 3)])

# Sort employees by Experience (ascending)
print("\nEmployees sorted by Experience (ascending):")
print(df.sort_values(by='Experience', ascending=True))


Original Employee Data:
    Name Department  Salary  Experience
0  Rafiq         HR   40000           2
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
3   Rima      Sales   45000           3
4  Faruk      Sales   47000           6

Employees with Salary > 45000:
    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
4  Faruk      Sales   47000           6

Employees from IT Department:
    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4

Employees with Salary > 45000 and Experience > 3:
    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
4  Faruk      Sales   47000           6

Employees sorted by Experience (ascending):
    Name Department  Salary  Experience
0  Rafiq         HR   40000           2
3   Rima      Sales   45000           3
2  Tuhin         

### City Weather Dashboard
data = {
 	'City': ['Dhaka', 'Sylhet', 'Chittagong', 'Rajshahi', 'Khulna'],
 	'Temp': [32, 28, 30, 35, 33],
 	'Humidity': [60, 75, 70, 55, 65]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Show only the cities where FeelsLike > 33.
 2. Sort the DataFrame by FeelsLike (descending).
 3. Find which city has the highest humidity.


In [33]:
import pandas as pd

data = {
    'City': ['Dhaka', 'Sylhet', 'Chittagong', 'Rajshahi', 'Khulna'],
    'Temp': [32, 28, 30, 35, 33],
    'Humidity': [60, 75, 70, 55, 65]
}

df = pd.DataFrame(data)

# Add a new column "FeelsLike" (simple formula combining Temp & Humidity)
# Example formula: FeelsLike = Temp + (Humidity / 100) * 5
df['FeelsLike'] = df['Temp'] + (df['Humidity'] / 100) * 5

print("City Weather Data:")
print(df)

# Show only the cities where FeelsLike > 33
print("\nCities where FeelsLike > 33:")
print(df[df['FeelsLike'] > 33])

# Sort the DataFrame by FeelsLike (descending)
print("\nData sorted by FeelsLike (descending):")
print(df.sort_values(by='FeelsLike', ascending=False))

# Find which city has the highest humidity
highest_humidity_city = df.loc[df['Humidity'].idxmax(), 'City']
print("\nCity with the highest humidity:", highest_humidity_city)


City Weather Data:
         City  Temp  Humidity  FeelsLike
0       Dhaka    32        60      35.00
1      Sylhet    28        75      31.75
2  Chittagong    30        70      33.50
3    Rajshahi    35        55      37.75
4      Khulna    33        65      36.25

Cities where FeelsLike > 33:
         City  Temp  Humidity  FeelsLike
0       Dhaka    32        60      35.00
2  Chittagong    30        70      33.50
3    Rajshahi    35        55      37.75
4      Khulna    33        65      36.25

Data sorted by FeelsLike (descending):
         City  Temp  Humidity  FeelsLike
3    Rajshahi    35        55      37.75
4      Khulna    33        65      36.25
0       Dhaka    32        60      35.00
2  Chittagong    30        70      33.50
1      Sylhet    28        75      31.75

City with the highest humidity: Sylhet
